#!/bin/bash
# Write a script that deletes all the regular files 
# (not the directories) with a .js extension that are present in the current directory an
# subfolders
find . -name "*.js" -type f -delete
