#!/usr/bin/env bash
# install nginx on a server
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html

text="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "19i $text" /etc/nginx/sites-available/default
service nginx restart
