#!/usr/bin/env bash
# install  nginx on a server
apt-get update
apt-get  -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
redirect="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "19i $redirect" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
error="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}"
sed -i "/server_name _;/a $error" /etc/nginx/sites-enabled/default
http_header="add_header X-Served-By $HOSTNAME;\n"
sed -i "20i $http_header" /etc/nginx/nginx.conf
service nginx restart

