#!/usr/bin/env bash
# A Bash script that configures the Nginx so that web-02 to be identical to web-01
apt-get update
apt-get -y install nginx
sed -i "31 i \\\n\tadd_header X-Served-By $HOSTNAME;\n" \
    /etc/nginx/sites-available/default
service nginx restart
