#!/usr/bin/env bash
# install and configuration HAproxit on lb-01 server

apt-get update
apt-get install -y haproxy=1.6.\*

echo "frontend http_front
	bind *:80
	stats uri /haproxy?stats
	default_backend http_back" >> /etc/haproxy/haproxy.cfg

echo "backend http_back
	balance roundrobin
	server 880-web-01 35.243.170.219:80 check
	server 880-web-02 35.237.154.254:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart

