#!/usr/bin/env bash
# configuration HAproxit
echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | \
      tee /etc/apt/sources.list.d/backports.list
apt-get update
apt-get install -y haproxy -t trusty-backports
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sed -i "6 i \\\nENABLED=1\n" /etc/default/haproxy
sed -i "\$a\
listen backend *:80\n\
\tmode http\n\tbalance roundrobin\n\
\tserver 123-web-01 35.243.170.219:80 check\n\
\tserver 123-web-02 35.237.154.254:80 check\n" \
/etc/haproxy/haproxy.cfg
sudo service haproxy start
