#!/usr/bin/env bash
# A Bash script that creates a /var/run/holbertonscript.pid file,
# displays a text indefinitely
# displays a text when receiving a SIGTERM signal
# displays a text when receiving a SIGINT signal
# deletes the file and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/holbertonscript.pid

trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me?!"' 2
trap 'rm /var/run/holbertonscript.pid' 3 15 


while :
do
	echo "To infinity and beyond"
	sleep 2
done

