#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond and I am invincible"
# when received a SIGTERM.


trap "echo I am invincible!!!" SIGINT SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
