#!/usr/bin/env bash
# This script display "Holberton School" and "hi"
i="0"
# lt is less than
while [ $i -lt 10 ];
    do
        echo "Holberton School"
        if (( i == 8 ));
        then
            echo "Hi"
        fi
        (( i++ ))
done
        

