#!/usr/bin/env bash
# This script display numbers and phrases

i="0"
# le is less or equal
while [ $i -le 20 ];
    do
        echo "$i"
        case $i in
            4) echo "bad luck from China";;
            9) echo "bad luck from Japan";;
            17) echo "bad luck from Italy";;
        esac
        (( i++ ))
done