#!/usr/bin/env bash
# script that shows time in 12 hours
# and 59 minutes
HOUR=0
while [ $HOUR -le 12 ];
    do
        echo "Hour: $HOUR"
        MIN=1
        while [ $MIN -le 59 ];
        do
            echo "$MIN"
            (( MIN++))
        done
        (( HOUR++))
done
