#!/usr/bin/env bash
# script to run Ngnix user 
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
